### ISSUE TITLE
Vendor should be commited

### ISSUE THREAD

**Issue by dameert** [theus77/elasticms#1]
After checkout the command `php bin/console server:run` does not work because the vendor directory is missing: 
> Warning: require(/Users/dameert/git/ElasticMS/app/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/dameert/git/ElasticMS/app/autoload.php on line 9

Because vendor versions are important to the committed state of the project, I think they should be included on git?

**Comment by dameert** [comment]
Better solution: add the composer lock file: The point of the lock file is to record the exact versions that are installed so they can be re-installed

**Comment by theus77** [comment]
Isn't the goal of the composer.json file? As far as I know, the "composer
update" command should take care of the dependencies (and create the vendor
folder)?


Here is the data model that i'm considering so far:

**Comment by theus77** [comment]
At this point I'll keep this ticket open. The composer.lock file will be added later.

**Comment by dameert** [comment]
I think this ticket can be closed. I undrestand composer.json better now..
As composer allows to target very specific versions of a bundle, the lock file can be very precise for everybody without having to commit it.
