### ISSUE TITLE
CollectionFieldType with mandatory = true always tells me there are empty fields

### ISSUE THREAD

**Issue by fiammybe** [theus77/elasticms#2]
I defined as part of a content type a CollectionFieldType. I want to have at least one element in that collection, so I set the Restriction as Mandatory = true. In that CollectionFieldType, all the underlying fields (a bunch of text fields) also have 'mandatory=true'.

When I am filling information in the content type, I permanently get the following errors : 
![image](https://cloud.githubusercontent.com/assets/3736946/25697294/acec0de4-30ba-11e7-9786-2e93fb6f30e7.png)

A workaround is to define the CollectionFieldType as not mandatory. I need this collection to be present and contain data though, so it's not a long term solution.

**Comment by fiammybe** [comment]
This is in v1.3.13

**Comment by ems-project** [comment]
So the mandatory constraint has been removed for the collection field in commit User/Repository@SHA: ems-project/EMSCoreBundle@c69200e04cfe68912e97437875683a15286ea207.
An issue to add a min and max constraint to the collection field has been created ems-project/EMSCoreBundle#2

**Comment by theus77** [comment]
See project/EMSCoreBundle#2
